//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CS.Bar {

using CS.Foo;

public class Bar : FooBarBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public Bar(global::System.IntPtr cPtr, bool cMemoryOwn) : base(cs_barPINVOKE.Bar_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Bar obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cs_barPINVOKE.delete_Bar(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override string GetName() {
    string ret = cs_barPINVOKE.Bar_GetName(swigCPtr);
    return ret;
  }

  public Bar() : this(cs_barPINVOKE.new_Bar(), true) {
  }

}

}
